url: https://blog.klarasimi.dev
title: "From Marketing to Tech"
name: 'Klara Simickova'
locale: "en-GB"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
 
remote_theme: "mmistakes/minimal-mistakes@4.14.2"

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
breadcrumbs: false
paginate: 5 # amount of posts to show
paginate_path: /page:num/

author:
  name     : "Klára Šimíčková"
  avatar   : "/images/profile_photo.jpg"
  bio      : "I left marketing to find my place in tech. Wish me luck, for I have not a slight idea what I am doing."
  location : "Prague, CZ" 
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/klarasimi"    
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/klarasimi"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/klarasimickova"

# analytics:
#  provider: "google-gtag"
#  google:
#    tracking_id: "UA-53402824-1"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/klarasimi"    
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/klarasimi"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/klarasimickova"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
related: false